version: '3.9'

services:
  postgresDb:
     restart: always
     image: postgres:16
     container_name: stonepostgres
     ports:
       - '5432:5432'
     environment:
        POSTGRES_PASSWORD: root
        POSTGRES_USER: root
        POSTGRES_DB: stonestarwars
     volumes:
       - pgData:/var/lib/postgresql/data

volumes:
  pgData: