version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresDb:5432/stonestarwars
      TOKEN_SECRET: ${TOKEN_SECRET}
    depends_on:
      - postgresDb
      - redisCache
    networks:
      - stone_networks
    links:
      - postgresDb
      - redisCache

  postgresDb:
     restart: always
     image: postgres:16
     container_name: stonepostgres
     ports:
       - '5432:5432'
     environment:
        POSTGRES_PASSWORD: root
        POSTGRES_USER: root
        POSTGRES_DB: stonestarwars
     volumes:
       - pgData:/var/lib/postgresql
     networks:
       - stone_networks

  redisCache:
    image: redis:latest
    restart: always
    volumes:
      - cache:/data
    ports:
      - '6379:6379'
volumes:
  pgData:
  cache:
  redis_insight_volume:
networks:
  stone_networks:
    driver: bridge