version: '3.9'

services:
  postgresDb:
     restart: always
     image: postgres:16
     container_name: stonepostgres
     ports:
       - '5432:5432'
     environment:
        POSTGRES_PASSWORD: root
        POSTGRES_USER: root
        POSTGRES_DB: stonestarwars
     volumes:
       - pgData:/var/lib/postgresql
     networks:
       - stone_networks
  redisCache:
    image: redis:latest
    restart: always
    volumes:
      - cache:/data
    ports:
      - 6379:6379
volumes:
  pgData:
  cache:
  redis_insight_volume:
networks:
  stone_networks:
    driver: bridge